### ISSUE TITLE
"set boiler warm tap water" results in weird boiler state

### ISSUE THREAD

**Issue by sysrun** [proddy/EMS-ESP-Boiler#26]
Just set the "set boiler warm tap water" to "off"

result was that my boiler went to a "5H 268" state - something like a "Relais-Test" - not sure.

What does the Tap-Water function mean?

**Comment by proddy** [comment]
oh, be careful with this function. What it does it switch the 3-valve stopping any hot tap water from flowing. I use this in my shower alarm logic and stole the idea from how the Nefit Easy (TC100) does it. The only way unfortunately to change this setting is to put the boiler into a Test Mode state. Make sure it's out of test mode otherwise your boiler will be basically nonfunctional.

**Comment by sysrun** [comment]
Ah, ok!
